### ISSUE TITLE
Update Sandbox database with stations/station deployments from Motus live

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1198]
Currently the Sandbox explore demo only has 12 station deployments being returned by the API.

In addition, all the station IDs in Sandbox are different from those in Live so copying deployments from Live into Sandbox for a working example isn't easy.

**Comment by cjardine-bsc** [comment]
Fixed.

**Comment by leberrigan** [comment]
Hmm.. I'm still seeing different station ID's in Sandbox vs. Live - is there a way to fix that?

**Comment by cjardine-bsc** [comment]
Nope. The stationIDs are different between the two DBs. What are you attempting to do?

**Comment by cjardine-bsc** [comment]
Imma close this one. I think you're good now that you've moved over to the live DB.

**Comment by denislepage** [comment]
A mean, lean, closing machine.
