### ISSUE TITLE
newly registered tags not detected

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#217]
Placeholder to record recently registered tags that aren't showing up in detection data until a fix is in place.

Project 90: 5 deployed tags should be on receiver SG-3115BBBK1151 (and possibly others)

project 123: no NTQB2-1 tags being detected, most likely will appear on receivers SG-1116BBBK0CEB and SG-4815BBBK0087.  A test was done on receiver SG-3615BBBK2700 with tags 28257, 28264, 28290, 28303, 28276

project 76: no NTQB2-1 tags, motusTagIDs 28022 - 28217 and 28222.  Tags registered 2018-03-15, deployed mid March to early April

project 177: two tags not detected 28219 and 28220 - likely same issue

**Comment by zcrysler** [comment]
Some of these tags started showing up for project 123 - does that mean this issue has been resolved? 
Tag in question is motusTagID 28313, being picked up on SG-3615BBBK01F1: https://sgdata.motus.org/download/123/SG-3615BBBK01F1-2016_BrustHELGO_23_Carolinensiel_hourly_tags.png

**Comment by cjardine-bsc** [comment]
Jeremy i think we can check that the receivers listed here have been re-run and close this issue.

**Comment by Hussell** [comment]
You're right, every receiver mentioned here has been rerun at least once, and all the tags mentioned have detections. (Except tag 28290, which still doesn't have a test deployment in metadata. Not our problem.)
