### ISSUE TITLE
Headers are messed up due to menu plugin upgrade

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#410]
See the homepage, for example.

Not sure who to assign this to...

**Comment by Hussell** [comment]
Fixed now, and I've reloaded the banner on live, beta, and sandbox. Thanks to whoever made the fix!

**Comment by denislepage** [comment]
I have been trying to resolve some issues with WordPress, IIS and PHP today. In the process, I updated the Drop Down Menu WP plugin to the latest version. This seems to have caused the problem. There must have been some changes to the CSS of the plugin that created this. I reverted to the previous version (still on sandbox), which seems to have resolved the issue.

Lesson learned, I guess. Updating plugins should always be done and tested on the sandbox before applying to live. We should try to figure out if this is something we can resolve to allow keeping the plugin updated. Maybe we'll try this in beta, since I had already messed that one too (currently reverted, but we can try to upgrade it again). Rather not mess with sandbox since it is working.

**Comment by denislepage** [comment]
Beta is updated now, and the issue is back.

I think we can figure out the CSS fixes needed.

If we add clear: both to the innercontainer class in 
https://beta.motus.org/wp-content/themes/motustheme/style.css

It partly fixes the problem, but stil leaves a gap on the right hand of the menu.

Jeremy, can you try to sort it out?

**Comment by denislepage** [comment]
It is also worth noting that we created some customized css for the menu, based I think on the default css for the plugin: https://beta.motus.org/styles/motus-menu.css

Whatever customization we did in this file may need to be carried over into their updated css.

**Comment by Hussell** [comment]
A fix for this is in place on the sandbox and beta servers. Please do *not* deploy to live yet, since this involved simultaneous changes to the headers in WordPress and some JS on the other side.

In short: rather than attempt to keep up with updates to the menu plugin, the plugin has been disabled and the menu replaced with a much simpler version which we have full control of. It *should* look and behave identically. Let me know if you spot any differences between the live and beta menus.

**Comment by denislepage** [comment]
Tested in Chrome, Firefox and Explorer 11. So far so good.

**Comment by Hussell** [comment]
Partially deployed to live. I'm keeping this issue open to remind me to get someone to remove the now unnecessary JavaScript files from the headers once the call has been removed from motusscripts.js on the live server. So, right after beta8 is released.

**Comment by Hussell** [comment]
I don't have permission to edit the headers on the live WordPress, so one of you will have to do it.

The line to remove is this one:
<script defer src='/wp-includes/js/hoverIntent.min.js?ver=r7'></script>

It should be removed from both header.php and strippedheader.php

**Comment by Hussell** [comment]
Looks like I got confused: the link to the script and a stylesheet were in a jspf include file. Removed from (and tested on beta).
